# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/kitsoft/plenary/models/category/fields.yaml

# Model Class name
modelClass: Kitsoft\Plenary\Models\Category

# Default redirect location
defaultRedirect: kitsoft/plenary/category

# Create page
create:
    title: Create Category
    redirect: kitsoft/plenary/category/update/:id
    redirectClose: kitsoft/plenary/category

# Update page
update:
    title: Edit Category
    redirect: kitsoft/plenary/category
    redirectClose: kitsoft/plenary/category

# Preview page
preview:
    title: Preview Category
