# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder

# Attribute name
nameFrom: title

# Model Class name
modelClass: KitSoft\Plenary\Models\Plenary

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
